name: test-deploy

on:
  push:
    branches:  add-workflow 
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

    - name: Install Dependencies
      run: |
        npm i
  
    - name: Setup Databse
      uses: harmon758/postgresql-action@v1
      with:
        postgresql db: 'my_db'
        postgresql user: 'test_user'
        postgresql password: 'test_password'

    - name: Seed Database
      run: | 
        export PGDATABASE=my_db
        export PGUSER=test_user
        export PGPASSWORD=test_password
        npm run seed

    - name: Run Tests
      run: |
        npm run test
  
  #deploy: