name: test-deploy

on:
  push:
    branches: main 
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

    - name: Install Dependencies
      run: |
        npm ci
  
    - name: Setup Databse
      uses: harmon758/postgresql-action@v1
      with:
        postgresql db: 'my_db'
        postgresql user: 'test_user'
        postgresql password: 'test_password'
        
    - name: Run Tests
      run: |
        export PGDATABASE=my_db
        export PGUSER=test_user
        export PGPASSWORD=test_password
        npm run test
  
  #deploy:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Render
        run: curl $\{{ secrets.RENDER_DEPLOY_HOOK_URL }}